const express = require('express');
const User = require('../models/User');
const router = express.Router();

// Initialize admin user
router.post('/init', async (req, res) => {
  try {
    const adminUsername = process.env.ADMIN_USERNAME || 'admin';
    const adminPassword = process.env.ADMIN_PASSWORD;
    
    if (!adminPassword) {
      return res.status(400).json({ 
        message: 'Admin password not configured. Please set ADMIN_PASSWORD environment variable.' 
      });
    }

    const adminExists = await User.findOne({ username: adminUsername });
    if (!adminExists) {
      const admin = new User({
        username: adminUsername,
        password: adminPassword,
        role: 'admin'
      });
      await admin.save();
      return res.json({ message: 'Admin user created successfully' });
    }
    // Ensure existing admin has admin role
    if (adminExists.role !== 'admin') {
      adminExists.role = 'admin';
      await adminExists.save();
      return res.json({ message: 'Admin user role updated' });
    }
    res.json({ message: 'Admin user already exists' });
  } catch (error) {
    res.status(500).json({ message: 'Error initializing admin', error: error.message });
  }
});

// Login - creates server-side session
router.post('/login', async (req, res) => {
  try {
    const { username, password } = req.body;

    if (!username || !password) {
      return res.status(400).json({ message: 'Username and password are required' });
    }

    const user = await User.findOne({ username });
    if (!user) {
      return res.status(401).json({ message: 'Invalid credentials' });
    }

    const isMatch = await user.comparePassword(password);
    if (!isMatch) {
      return res.status(401).json({ message: 'Invalid credentials' });
    }

    // Create session data (session ID is already generated by express-session)
    req.session.userId = user._id.toString();
    req.session.username = user.username;
    req.session.role = user.role;

    // Get session ID
    const sessionId = req.sessionID;
    console.log('Session ID:', sessionId);
    console.log('Session data to save:', {
      userId: req.session.userId,
      username: req.session.username,
      role: req.session.role
    });

    // Save session using promise
    await new Promise((resolve, reject) => {
      req.session.save((err) => {
        if (err) {
          console.error('Session save error:', err);
          reject(err);
        } else {
          console.log('Session saved successfully, ID:', req.sessionID);
          resolve();
        }
      });
    });

    // Verify session was saved by trying to retrieve it (with timeout)
    try {
      const savedSession = await Promise.race([
        new Promise((resolve, reject) => {
          req.sessionStore.get(sessionId, (err, session) => {
            if (err) reject(err);
            else resolve(session);
          });
        }),
        new Promise((_, reject) => 
          setTimeout(() => reject(new Error('Session verification timeout')), 2000)
        )
      ]);

      if (!savedSession) {
        console.error('WARNING: Session not found in store after save!');
      } else {
        console.log('Session verified in store, userId:', savedSession.userId);
      }
    } catch (verifyError) {
      console.error('Error verifying session save:', verifyError.message);
      // Continue anyway - session might still be saved
    }

    // Log cookie information for debugging
    console.log('Login response - Cookie info:', {
      sessionId: sessionId,
      cookieHeader: res.getHeader('Set-Cookie'),
      cookiesInRequest: req.headers.cookie ? 'present' : 'missing'
    });

    // Return session ID for React Native (since cookies don't work well)
    // Session ID is just an identifier, actual session data stays on server
    // For web clients, the cookie is automatically set by express-session
    res.json({
      success: true,
      sessionId: sessionId, // Also return for web clients in case they need it
      user: {
        id: user._id.toString(),
        username: user.username,
        role: user.role
      }
    });
  } catch (error) {
    console.error('Login error:', error);
    res.status(500).json({ message: 'Error logging in', error: error.message });
  }
});

// Logout - destroys session
router.post('/logout', (req, res) => {
  req.session.destroy((err) => {
    if (err) {
      console.error('Session destroy error:', err);
      return res.status(500).json({ message: 'Error logging out', error: err.message });
    }
    res.clearCookie('spentee.sid');
    res.json({ success: true, message: 'Logged out successfully' });
  });
});

// Check authentication status
router.get('/me', async (req, res) => {
  try {
    let session = req.session;
    
    // Support session ID header for React Native
    if (req.headers['x-session-id'] && !session?.userId) {
      const sessionId = req.headers['x-session-id'];
      session = await new Promise((resolve, reject) => {
        req.sessionStore.get(sessionId, (err, sess) => {
          if (err) reject(err);
          else resolve(sess);
        });
      });
    }

    if (!session || !session.userId) {
      return res.status(401).json({ message: 'Not authenticated' });
    }

    const user = await User.findById(session.userId).select('-password');
    if (!user) {
      if (req.headers['x-session-id']) {
        await new Promise((resolve) => {
          req.sessionStore.destroy(req.headers['x-session-id'], resolve);
        });
      } else {
        req.session.destroy();
      }
      return res.status(401).json({ message: 'User not found' });
    }

    res.json({
      user: {
        id: user._id,
        username: user.username,
        role: user.role
      }
    });
  } catch (error) {
    console.error('Auth check error:', error);
    res.status(500).json({ message: 'Error checking authentication', error: error.message });
  }
});

module.exports = router;


